name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Job1:
    runs-on: local
    steps:
      - name: whoami
        run: |
          whoami
      - name: env
        run: |
          env
      - name: sleep
        run: |
          sleep 5
